apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop
  labels:
    role: api
    env: demo
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-api=public.ecr.aws/h9l8e8o4/my-api-repo
    argocd-image-updater.argoproj.io/my-api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: HEAD
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
        - name: api
          image: public.ecr.aws/h9l8e8o4/my-api-repo:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: mongo-sec1
                  key: connection_string
          ports:
            - containerPort: 5001
          livenessProbe:
            httpGet:
              path: /ok
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ok
              port: 5001
            initialDelaySeconds: 10
