apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: workshop
spec:
  ports:
    - port: 5001            # Expose the service on port 5001
      targetPort: 5001      # Redirect traffic to port 5001 in the container
      protocol: TCP
  type: LoadBalancer         # Expose the service externally via LoadBalancer
  selector:
    role: api                # Matches the role label of your pods
