apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: workshop
  name: argocd-deployment-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-deployment-role-binding
  namespace: workshop
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
roleRef:
  kind: Role
  name: argocd-deployment-role
  apiGroup: rbac.authorization.k8s.io
