apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume-claim
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
