apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim-new
  namespace: workshop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
