apiVersion: v1
kind: Secret
metadata: 
  namespace: workshop
  name: mongo-sec
type: Opaque
data:  
  password: cGFzc3dvcmQxMjM=  # "password123"
  username: YWRtaW4=  # "admin"
  connection_string: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdkYi1zdmM6MjcwMTcvdG9kbz9hdXRoU291cmNlPWFkbWlu  # "mongodb://admin:password123@mongodb-svc:27017/todo?authSource=admin"
