

# replicaCount: 1

# image:
#   repository: mongo
#   pullPolicy: IfNotPresent
#   tag: "4.4.6"

# imagePullSecrets: []

# nameOverride: ""
# fullnameOverride: ""

# serviceAccount:
#   create: true
#   automount: true
#   annotations: {}
#   name: ""

# podAnnotations: {}
# podLabels: {}

# podSecurityContext: {}
# securityContext: {}

# service:
#   type: ClusterIP
#   port: 27017

# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []

# resources: {}

# livenessProbe:
#   httpGet:
#     path: /
#     port: http

# readinessProbe:
#   httpGet:
#     path: /
#     port: http

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80

# volumes: []

# volumeMounts: []

# nodeSelector: {}

# tolerations: []

# affinity: {}

# # ➕ MONGO CONNECTION STRING SECTION (used in secrets.yaml)
# mongo:
#   url: "mongodb://admin:password123@mongodb-mongodb-chart:27017/todo?authSource=admin"



# Default values for database-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "4.4.6"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 27017

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# ➕ MONGO CONNECTION STRING SECTION (used in secrets.yaml)
mongo:
  url: "mongodb://admin:password123@mongodb-mongodb-chart:27017/todo?authSource=admin"
