apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
<<<<<<< HEAD
        image:  public.ecr.aws/h9l8e8o4/python-deployment:latest
=======
        image: public.ecr.aws/h9l8e8o4/python-deployment:latest # Space added after colon
>>>>>>> 6baeaa0 (WIP: local changes before rebase)
        imagePullPolicy: Always
        ports: 
        - containerPort: 5002
